#!/bin/bash

# Function to extract A record info
get_record_info() {
    local full_subdomain=$1
    dig $full_subdomain +short | awk '{print "The subdomain " subdomain " is a A record and points to " $1}' subdomain=$2
}

# Main logic
domain=$1
subdomain=$2

if [ -z "$domain" ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

if [ -n "$subdomain" ]; then
    get_record_info "$subdomain.$domain" "$subdomain"
else
    for sd in www lb-01 web-01 web-02; do
        get_record_info "$sd.$domain" "$sd"
    done
fi
